apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-vm
  namespace: vmexamples
  labels:
    app: my-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: my-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 4Gi
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: my-vm-pvc
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: "kubevirt"
            chpasswd: { expire: False }
            ssh_pwauth: True
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vm-pvc
  namespace: vmexamples
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd # ODF/OCS storage class
